# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 17:43
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User

from mturk.management.commands.InitMTurkData import create_initial_data


def init_data(apps, schema_editor):
    """
    Initialize the mturk database with data.
    """
    appName = "mturk"

    # @note - there seems to be some kind of weird issue with the
    #     User model. When I get the 'User' model using the
    #     'apps' variable, that fake "User" model does not allow
    #     me to run `create_user` because it complains about a
    #     missing 'normalize_username' method.
    #     But if I attempt to create the object first using the
    #     model in django.contrib.auth.models, later my scripts
    #     will get the user from the fake model fine and be able
    #     to generate the necessary data as expected

    try:
        mturk = User.objects.get(username = "mturk")
    except User.DoesNotExist:
        mturk = User.objects.create_user(
            username="mturk",
            password="mturk",
            first_name="MTurk",
            last_name="Emulator"
        )

    modelNames = ["Worker", "Requester", "Qualification", "Locale"]
    models = {
        "User" : apps.get_model("auth", "User")
    }
    for modelName in modelNames:
        models[modelName] = apps.get_model(appName, modelName)

    create_initial_data(**models)


class Migration(migrations.Migration):
    """
    Data Migration that initializes the database with the necessary
    system qualifications for the mturk system.
    """
    dependencies = [
        ('mturk', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_data),
    ]
